@startuml
!define MONO_BEHAVIOUR <<(M,#c593fa)>>
!define NETWORK_BEHAVIOUR <<(N,#FF7700)>>
!define INTERFACE <<(I,#00d0ff)>>

package "Interfaces" {
    interface IInteractable INTERFACE {
      +Interact(ulong clientID)
      +ulong GetNetworkObjectID()
    }
    interface IGrabbable INTERFACE {
      +AddGrabber(ulong clientId, Transform holdPoint)
      +RemoveGrabber(ulong clientId)
      +ulong GetNetworkObjectID()
    }
    interface ISnappable INTERFACE {
        +bool isSnapped
        +SnapZone currentZone
        +SnapTo(SnapZone zone)
        +Unsnap()
    }
    interface IEffectable INTERFACE {
        +ApplyEffect(string effectName, float duration)
    }
}

package "Events" {
    static class EventBus <<Static>> {
        +Subscribe<T>(Action<T> listener)
        +Unsubscribe<T>(Action<T> listener)
        +Publish<T>(T eventItem)
    }
    
    struct OnInject <<IEvent>> {
        +ulong VictimID
        +InyeccionType Type
    }
    struct OnAlienHealthChanged <<IEvent>> {
        +float CurrentHealth
        +float MaxHealth
    }
    struct OnAlienDeath <<IEvent>> {
        +ulong AlienID
    }
    struct OnBloodBagSnapped <<IEvent>> {
        +ulong BloodBagID
    }
    struct OnBloodBagDetached <<IEvent>> {
        +ulong BloodBagID
    }
}

package "Core Player" {
    class PlayerInput NETWORK_BEHAVIOUR {
      +Vector2 MovementInput
      +Vector2 LookInput
      +event Action OnJumpPressed
      +event Action OnPickUpPressed
      +event Action OnInteractPressed
      +event Action OnSlipPressed
    }
    class PlayerController NETWORK_BEHAVIOUR {
      -Rigidbody rigidBody
      +Ragdoll(bool active)
      -Move()
      -Jump()
    }
    class PlayerCamera NETWORK_BEHAVIOUR {
      -Transform playerCam
    }
    class PlayerInteractor NETWORK_BEHAVIOUR {
      -IGrabbable currentlyGrabbedItem
      +Ragdoll(bool active)
      -TryGrabOrThrow()
      -TryInteract()
    }
    class PlayerStateManager NETWORK_BEHAVIOUR {
      -float stunDuration
      +Slip()
      -EnterRagdoll(float ragdollTime)
      -RecoverJump()
      -ExitRagdoll()
      +ApplyInyeccion(InyeccionType type)
      +ApplyEffect(string effectName, float duration)
    }
}

package "Environment & Hazards" {
    class PuddleSpawner MONO_BEHAVIOUR {
        +static Instance
        +GameObject puddlePrefab
        +SpawnPuddleServerRpc(Vector3 position, float duration)
    }
    class BloodPuddle NETWORK_BEHAVIOUR {
        -float effectDuration
        -OnTriggerEnter(Collider other)
        -DespawnPuddle()
    }
}

package "Items & Physics" {
    class PhysicalItem NETWORK_BEHAVIOUR {
      -Rigidbody rb
      -Dictionary<ulong, Transform> grabbers
      -FixedUpdate() : Hookes Law
      +AddGrabber(ulong clientId, Transform holdPoint)
      +RemoveGrabber(ulong clientId)
    }
    class SnappableItem NETWORK_BEHAVIOUR {
        +SnapType itemType
        +bool isSnappable
        +bool isUnsnappable
        +SnapTo(SnapZone zone)
        +Unsnap()
    }
    class InteractableItem NETWORK_BEHAVIOUR {
      +UnityEvent onInteract
      +Interact(ulong clientID)
    }
    enum SnapType {
        Enchufe
        Bateria
        Diente
        Venda
        Jeringuilla
        Bloodbag
    }
}

package "Snap & Power System" {
    class SnapZone NETWORK_BEHAVIOUR {
        +SnapType acceptedType
        +Transform snapAnchor
        +UnityEvent OnObjectSnapped
        +UnityEvent OnObjectUnsnapped
        +SnappableItem currentItem
        -OnTriggerEnter(Collider other)
        +ReleaseItem()
    }
    class PowerReceiver NETWORK_BEHAVIOUR {
        +NetworkVariable<bool> hasPower
        -PowerEmitter[] wiredEmiters
        -PoweredItem toolToPower
        +SetPower(bool isPowered, PowerEmitter emiter)
    }
    class PowerEmitter NETWORK_BEHAVIOUR {
        +NetworkVariable<bool> hasPower
        -PowerReceiver connectedReceiver
        +OnPlug()
        +OnUnplug()
        +SetEmitting(bool emitting)
    }
    class PoweredItem NETWORK_BEHAVIOUR {
        +int energyLoad
        +NetworkVariable<bool> isTurnedOn
        +NetworkVariable<bool> hasPower
        +SetPowered(bool powered)
        +Interact(ulong clientID)
    }
}

package "Tools & Mechanics" {
    class LuzBehaviour NETWORK_BEHAVIOUR {
        +Transform originPoint
        +float rayDistance
        -EmitLight()
        -NotifyHealWoundServerRpc()
        -RequestNewWoundServerRpc()
    }
}

package "Alien System" {
    class AlienStateManager NETWORK_BEHAVIOUR {
      +NetworkVariable<float> currentHealth
      +ApplyInyeccion(InyeccionType type)
      +OnBloodBagConnected(OnBloodBagSnapped e)
    }
    class AlienWoundManager NETWORK_BEHAVIOUR {
      +GameObject woundPrefab
      +GenerateWound(Vector3 position, Vector3 normal)
    }
    class WoundBehaviour NETWORK_BEHAVIOUR {
      +float healingTimeRequired
      +ReceiveHealTick()
    }
}

' Relaciones Core Player
PlayerController o-- PlayerInput
PlayerCamera o-- PlayerInput
PlayerInteractor o-- PlayerInput
PlayerStateManager -left-> PlayerController
PlayerStateManager -left-> PlayerInteractor

PlayerInteractor ---> IGrabbable
PlayerInteractor ---> IInteractable

' Relaciones Hazards
PlayerStateManager .up.|> IEffectable
BloodPuddle ..> IEffectable : "Llama a ApplyEffect()"
PuddleSpawner ..> BloodPuddle : "Spawnea"

' Relaciones Items & Snap
PhysicalItem .up.|> IGrabbable
InteractableItem .up.|> IInteractable
SnappableItem .up.|> ISnappable
SnappableItem -right-> PhysicalItem
SnapZone o-- SnappableItem

' Relaciones Power System
PoweredItem -up-|> InteractableItem
PowerEmitter o-- PowerReceiver : "Conecta con"
PowerReceiver o-- PowerEmitter : "Puede tener hijos (Alargador)"
PowerReceiver o-- PoweredItem : "Da energía a herramienta"
SnapZone ..> PowerEmitter : "Eventos (OnObjectSnapped)"

' Relaciones Tools y Alien System
LuzBehaviour ..> WoundBehaviour : "Cura (HealTick)"
LuzBehaviour ..> AlienWoundManager : "Crea heridas"

' Relaciones EventBus
SnapZone ..> EventBus : "Publish<OnBloodBagSnapped/Detached>"
AlienStateManager ..> EventBus : "Subscribe<OnBloodBagSnapped/Detached>"

@enduml