@startuml
!define MONO_BEHAVIOUR <<(M,#c593fa)>>
!define NETWORK_BEHAVIOUR <<(N,#FF7700)>>
!define INTERFACE <<(I,#00d0ff)>>

package "Interfaces" {
    interface IInteractable INTERFACE {
      +Interact(ulong clientID)
      +ulong GetNetworkObjectID()
    }
    interface IGrabbable INTERFACE {
      +AddGrabber(ulong clientId, Transform holdPoint)
      +RemoveGrabber(ulong clientId)
      +ulong GetNetworkObjectID()
    }
    interface IUsable INTERFACE {
      +UseStart(ulong clientId)
      +UseStop(ulong clientId)
      +ulong GetNetworkObjectID()
    }
    interface ISnappable INTERFACE {
        +SnapTo(SnapZone zone)
        +Unsnap()
    }
}
package "Events" {
    static class EventBus <<Static>> {
        +Subscribe<T>(Action<T> listener)
        +Unsubscribe<T>(Action<T> listener)
        +Publish<T>(T eventItem)
    }
    
    struct OnInject <<IEvent>> {
        +ulong VictimID
        +InyeccionType Type
    }
}
package "Core Player" {
    class PlayerInput NETWORK_BEHAVIOUR {
      +Vector2 MovementInput
      +Vector2 LookInput
      +event Action OnJumpPressed
      +event Action OnPickUpPressed
      +event Action OnInteractPressed
      +event Action OnSlipPressed
    }
    class PlayerController NETWORK_BEHAVIOUR {
      -Rigidbody rigidBody
      +Ragdoll(bool active)
      -Move()
      -Jump()
    }
    class PlayerCamera NETWORK_BEHAVIOUR {
      -Transform playerCam
    }
    class PlayerInteractor NETWORK_BEHAVIOUR {
      -IGrabbable currentlyGrabbedItem
      +Ragdoll(bool active)
      -TryGrabOrThrow()
      -TryInteract()
      +InteractServerRpc()
      +GrabObjectServerRpc()
      +ReleaseObjectServerRpc()
    }
    class PlayerStateManager NETWORK_BEHAVIOUR {
      -float stunDuration
      +Slip()
      -EnterRagdoll(float ragdollTime)
      -RecoverJump()
      -ExitRagdoll()
      -OnPlayerInjected(OnInject data)
    }
}
package "Items & Physics" {
    package "Inyecciones" {
      class InyecionItem {
        -InyeccionType inyeccionType
        +Inject(Gameobject victim)
      }
      class InyeccionCollider {
        -InyeccionItem inyeccionItem
        -OnTriggerEnter(Collider other)
      }
    }
    class PhysicalItem NETWORK_BEHAVIOUR {
      -Rigidbody rb
      -Dictionary<ulong, Transform> grabbers
      -FixedUpdate() : Hookes Law
      +AddGrabber(ulong clientId, Transform holdPoint)
      +RemoveGrabber(ulong clientId)
      -NotifyHoldingToolClientRpc(bool holding, ulong targetClientId)
    }
    class SnappableItem NETWORK_BEHAVIOUR {
        +SnapType itemType
        -PhysicalItem physics
        +SnapTo(SnapZone zone)
        +Unsnap()
    }
    class InteractableItem NETWORK_BEHAVIOUR {
      +UnityEvent onInteract
      +Interact(ulong clientID)
    }
}

package "Snap & Power" {
    class SnapZone NETWORK_BEHAVIOUR {
        +SnapType acceptedType
        +Transform snapAnchor
        -ISnappable currentItem
        +OnTriggerEnter(Collider other)
    }
    class PowerReceiver MONO_BEHAVIOUR {
        +bool isPowered
        +OnPowerStatusChanged
    }
}

package "Alien System" {
    class AlienStateManager NETWORK_BEHAVIOUR {
      +enum State { Calmado, Alterado, Critico, Dañado }
      +float health
      +float calmantDuration
      +ChangeState(State newState)
      +TakeDamage(float amount)
      +Heal(float amount)
    }
}

PlayerController o-- PlayerInput
PlayerCamera o-- PlayerInput
PlayerInteractor o-- PlayerInput
PlayerStateManager -left-> PlayerController
PlayerStateManager -left-> PlayerInteractor

PhysicalItem .up.|> IGrabbable
InteractableItem .up.|> IInteractable
SnappableItem .up.|> ISnappable

SnappableItem -right-> PhysicalItem
SnapZone o-- ISnappable

PlayerInteractor ---> IGrabbable
PlayerInteractor ---> IInteractable
PlayerInteractor ---> IUsable

' InyeccionItem publica el evento a través del EventBus
InyecionItem ..> EventBus : "Publish<OnInject>"
InyecionItem ..> OnInject : "creates"

AlienStateManager ..> EventBus : "Subscribes to OnInject"
PlayerInteractor ..> EventBus : "Subscribes to OnInject"
@enduml